import { Platform, StatusBar, StyleSheet, Dimensions } from "react-native";
import { Theme } from "@/hooks/useThemeColor";

const windowWidth = Dimensions.get("window").width;
const isDesktop = windowWidth > 1024;

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.backgroundColor,
      ...(isDesktop && {
        paddingHorizontal: 40,
        paddingVertical: 30,
      }),
    },
    innerContainer: {
      flex: 1,
      backgroundColor: theme.backgroundColor,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.borderColor,
      overflow: "hidden",
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.1,
      shadowRadius: 15,
      elevation: 10,
      ...(isDesktop && {
        maxWidth: 1200,
        marginHorizontal: "auto",
      }),
    },
    scrollView: {
      flex: 1,
    },
    scrollViewContent: {
      flexGrow: 1,
      padding: 20,
      paddingTop: 20, // Add some top padding
      ...(isDesktop && {
        paddingHorizontal: 60,
        paddingTop: 40, // Increase top padding for desktop
        paddingBottom: 40, // Add bottom padding for desktop
      }),
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "600",
      color: theme.sectionTitleColor,
      marginBottom: 10,
      marginTop: 20,
      alignSelf: "flex-start",
      fontFamily: "Helvetica Neue, sans-serif",
      textShadowColor: "rgba(0, 0, 0, 0.1)",
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 2,
      ...(isDesktop && {
        fontSize: 24,
        marginTop: 10,
        marginBottom: 5,
      }),
    },
    styleList: {
      flexDirection: "row",
      flexWrap: "nowrap",
      justifyContent: "flex-start",
      alignItems: "center",
      marginBottom: 15,
      paddingBottom: 5,
      ...(isDesktop && {
        marginBottom: 10,
        overflowX: "auto",
        width: "100%",
      }),
    },
    keywordSection: {
      marginBottom: 5,
      ...(isDesktop && {
        marginBottom: 20,
      }),
    },
    selectedKeywordsContainer: {
      flexDirection: "row",
      flexWrap: "wrap",
      marginBottom: 5,
      marginTop: 10,
      alignSelf: "flex-start",
      ...(isDesktop && {
        marginTop: 6,
        marginBottom: 6,
      }),
    },
    selectedKeyword: {
      backgroundColor: theme.secondaryColor,
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 20,
      marginRight: 8,
      marginBottom: 8,
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    selectedKeywordText: {
      color: theme.selectedKeywordTextColor,
      fontSize: 14,
      fontFamily: "Helvetica Neue, sans-serif",
    },
    generateButton: {
      backgroundColor: theme.primaryColor,
      paddingVertical: 14,
      paddingHorizontal: 30,
      borderRadius: 25,
      alignItems: "center",
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 5,
      ...(isDesktop && {
        marginTop: 30,
        marginBottom: 30,
        paddingVertical: 18,
        paddingHorizontal: 40,
      }),
    },
    buttonText: {
      color: theme.buttonTextColor,
      fontSize: 16,
      fontWeight: "600",
      fontFamily: "Helvetica Neue, sans-serif",
      letterSpacing: 0.5,
    },
    infoText: {
      color: theme.textColor,
      fontSize: 16,
      marginBottom: 15,
      ...(isDesktop && {
        fontSize: 18,
        marginBottom: 25,
      }),
    },
    errorText: {
      color: theme.errorColor,
      fontSize: 16,
      marginBottom: 15,
      ...(isDesktop && {
        fontSize: 18,
        marginBottom: 25,
      }),
    },
    garmentName: {
      fontSize: 20,
      fontWeight: "600",
      color: theme.sectionTitleColor,
      marginBottom: 15,
      marginTop: 10,
      textAlign: "center",
      fontFamily: "Helvetica Neue, sans-serif",
      ...(isDesktop && {
        fontSize: 28,
        marginTop: 30,
        marginBottom: 25,
      }),
    },
    imageContainer: {
      width: "100%",
      aspectRatio: 1,
      maxWidth: 500,
      marginTop: 10,
      borderRadius: 20,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: theme.separatorColor,
      backgroundColor: theme.backgroundColor,
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.2,
      shadowRadius: 15,
      elevation: 15,
      ...(isDesktop && {
        marginTop: 30,
        marginBottom: 30,
      }),
    },
    image: {
      width: "100%",
      height: "100%",
    },
    generatedImageContainer: {
      position: "relative",
      marginRight: 15,
      marginBottom: 15,
    },
    thumbnailImage: {
      width: 120,
      height: 120,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.separatorColor,
    },
    saveButton: {
      position: "absolute",
      bottom: 8,
      right: 8,
      backgroundColor: "rgba(0,0,0,0.6)",
      borderRadius: 20,
      padding: 8,
    },
    saveButtonMain: {
      backgroundColor: theme.primaryColor,
      padding: 15,
      borderRadius: 25,
      alignItems: "center",
      marginBottom: 25,
      marginTop: 10,
      shadowColor: theme.primaryColor,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 8,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.8)",
      justifyContent: "center",
      alignItems: "center",
    },
    enlargedImage: {
      width: "90%",
      height: "70%",
      borderRadius: 20,
      borderWidth: 3,
      borderColor: theme.primaryColor,
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.5,
      shadowRadius: 20,
      elevation: 20,
    },
    descriptionContainer: {
      alignSelf: "flex-start",
      width: "100%",
      ...(isDesktop && {
        marginTop: 30,
        marginBottom: 30,
      }),
    },
    descriptionText: {
      fontSize: 14,
      color: theme.descriptionTextColor,
      marginTop: 8,
      fontFamily: "Helvetica Neue, sans-serif",
      lineHeight: 20,
      ...(isDesktop && {
        fontSize: 18,
        lineHeight: 28,
      }),
    },
    buttonContainer: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 20,
      marginTop: 10,
      paddingHorizontal: 10,
      ...(isDesktop && {
        marginTop: 30,
        marginBottom: 10,
      }),
    },
    upgradeSection: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 30,
      marginBottom: 30,
      paddingHorizontal: 20,
      paddingVertical: 15,
      backgroundColor: `${theme.secondaryColor}CC`,
      borderRadius: 15,
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.1,
      shadowRadius: 10,
      elevation: 5,
      ...(isDesktop && {
        marginTop: 50,
        marginBottom: 50,
        paddingHorizontal: 30,
        paddingVertical: 25,
      }),
    },
    upgradeText: {
      flex: 1,
      color: theme.textColor,
      fontSize: 16,
      marginRight: 15,
      fontFamily: "Helvetica Neue, sans-serif",
    },
    upgradeButton: {
      backgroundColor: theme.primaryColor,
      paddingVertical: 12,
      paddingHorizontal: 20,
      borderRadius: 25,
      alignItems: "center",
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 8,
    },
    upgradeButtonText: {
      color: theme.backgroundColor,
      fontSize: 16,
      fontWeight: "600",
      fontFamily: "Helvetica Neue, sans-serif",
    },
    buttonRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      width: "100%",
      marginBottom: 5,
      marginTop: 10,
    },
    pinterestButton: {
      backgroundColor: "#BD081C",
      paddingVertical: 14,
      paddingHorizontal: 20,
      borderRadius: 25,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 3,
      elevation: 4,
      marginTop: 10,
      marginBottom: 20,
      ...(isDesktop && {
        marginTop: 30,
        marginBottom: 40,
      }),
    },
    pinterestButtonText: {
      color: "#FFFFFF",
      fontWeight: "600",
      fontSize: 16,
      fontFamily: "Helvetica Neue, sans-serif",
      marginLeft: 8,
    },
    generateButtonDisabled: {
      opacity: 0.5,
    },
    placeHolderText: {
      color: theme.textColor,
      fontSize: 16,
      marginTop: 10,
      fontFamily: "Helvetica Neue, sans-serif",
    },
    garmentNameContainer: {
      marginBottom: 10,
    },
    garmentNameText: {
      color: theme.textColor,
      fontSize: 20,
      fontWeight: "600",
      fontFamily: "Helvetica Neue, sans-serif",
    },
    themeToggleButton: {
      padding: 10,
      alignSelf: "flex-end",
      marginRight: 10,
      marginTop: 10,
    },
    themeToggleText: {
      fontSize: 16,
      fontWeight: "600",
      color: theme.textColor,
    },
    button: {
      marginRight: 10,
      marginBottom: 10,
      borderRadius: 20, // Increased from 15
      overflow: "hidden",
    },
    buttonGradient: {
      paddingHorizontal: 16, // Increased from 12
      paddingVertical: 10, // Increased from 8
    },
    buttonText: {
      color: theme.textColor,
      fontSize: 16, // Increased from 14
      fontWeight: "bold",
    },
    selectedButton: {
      // You can add any additional styles for selected state here
      // For example, you might want to add a border:
      borderWidth: 2,
      borderColor: theme.accentColor,
    },
    selectedButtonText: {
      color: theme.accentColor,
    },
  });
